feat: create instance sample
devopssobral/terraform_demo pull request #1
Opened 2022-04-17 22:19 UTC by george124816

2022-04-17 22:20 UTC, george124816 commented on main.tf
> +  }
criei esse bucket pro tfstate em outro repo, qual seria a melhor prática pra isso?

2022-04-17 22:32 UTC, george124816 commented
qual seria melhor prática pra criar o "aws_key_pair"? não parece ser uma boa ideia jogar a chave pública direta aqui 
@edsoncelio

2022-04-17 22:33 UTC, edsoncelio requested changes

2022-04-17 22:33 UTC, edsoncelio commented on main.tf
> +  }
Sem problema, pro primeiro state faz sentido deixar a criação dele em um repo diferente, e pro nosso caso não vamos focar nisso, só falar que precisa criar um bucket com antecedência e tals.

A recomendação aqui que criasse um arquivo separado só pro backend, e chamasse ele de `backend.tf` pra isolar por responsabilidade.

2022-04-17 22:33 UTC, edsoncelio commented on main.tf
> +data "aws_ami" "ubuntu" {
Aqui pode criar um arquivo `data.tf` e colocar esse trecho de data lá

2022-04-17 22:33 UTC, edsoncelio commented on main.tf
> +resource "aws_vpc" "main" {
Aqui tá criando uma nova VPC, pode usar um data pra buscar os dados da VPC default e usar ela:
```
data "aws_vpc" "selected" {
  default = true
}
```

E ai pode usar com `data.aws_vpc.selected.id`

2022-04-17 22:35 UTC, edsoncelio commented
> qual seria melhor prática pra criar o "aws_key_pair"? não parece ser uma boa ideia jogar a chave pública direta aqui @edsoncelio

Pode usar um resource do provider `tls_provider` ou pra simplificar agora só cria uma chave manualmente e adiciona ela nos argumentos da EC2, ai depois a gente cria a chave.

2022-04-18 16:03 UTC, cassioliveiram reviewed
Sugiro tambem a criação de um .gitignore pra nao subir junto com o codio partes do estado, dai se tu precisa de uma versao especifica dos providers, tambem da pra definirum version.tf :)

2022-04-18 21:48 UTC, george124816 commented
@cassioliveiram vacilei e mandei o `.gitignore` direto pra main, mas lá já tem os tfstates,
vou dar uma olhada no `version.tf`

2022-04-23 14:46 UTC, closed without merging